### ISSUE TITLE
Cannot disable semicolon

### ISSUE THREAD

**Issue by DVLP** [unlight/sublime-import-helper#105]
Using no semicolon in ES6 is a common practice. It seems like _from_semicolon_ used to be available but it was later removed. Can this option be restored?

**Comment by unlight** [comment]
Unfortunately, `ts-morph` (which is used under the hood) does not provide such settings
See similar issue https://github.com/unlight/sublime-import-helper/issues/97

**Comment by DVLP** [comment]
What about a workaround and automatic trimming of the semicolon after the import line is created?

**Comment by unlight** [comment]
Need to investigate

**Comment by DVLP** [comment]
I opened an issue in ts-morph. Is this what's needed? https://github.com/dsherret/ts-morph/issues/1200

**Comment by unlight** [comment]
Released in 4.0.0

**Comment by DVLP** [comment]
Thank you! Just tried in ST4 and works well. Regular package upgrade didn't work at first. Something about "settings" parameter. After reinstalling and restarting Sublime works well.
