### ISSUE TITLE
Add a way to ignore folders/paths in project folder(s)

### ISSUE THREAD

**Issue by tukusejssirs** [unlight/sublime-import-helper#106]
I code in TypeScript, which needs to be compiled into JavaScript. We usually use `dist/` folder in the repo (project) root folder.

Now when I already have built the code (i.e. `dist/` folder already exists) and try to auto-import something that is both in the source and `dist/`, auto-import asks me to choose which one to import.

It might be a good idea to add an option to ignore some folders/paths. It should be an array of paths relative to the project folder(s). When there are more project folders, I suggest to ignore all matched paths in all project folders.

**Comment by unlight** [comment]
It should work with folder_exclude_patterns setting in sublime project file. Add dist path to folder_exclude_patterns, see https://www.sublimetext.com/docs/projects.html#folders

**Comment by tukusejssirs** [comment]
Thanks, @unlight!

The solution is to add `folder_exclude_patterns` array to the project file (`Project` → `Edit project`):

```js
{
  "folders":
  [
    {
      "path": "/absolute/path/to/project/root/folder",
      // Note: `//` at the beginning tells ST4+ it should match the pattern only in the project root
      "folder_exclude_patterns": ["//dist/", "//temp/"]
    }
  ],
}
```
