### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'node'

### ISSUE THREAD

**Issue by S1ngS1ng** [unlight/sublime-import-helper#107]
Hi. Here is the error from my local machine:

```
error: Import Helper
Traceback (most recent call last):
  File "/Users/singliu/Library/Application Support/Sublime Text/Packages/ImportHelper/library/exec_command.py", line 18, in run_command
    (err, out) = exec([NODE_BIN, "--no-warnings", RUN_PATH], json)
  File "/Users/singliu/Library/Application Support/Sublime Text/Packages/ImportHelper/library/exec_command.py", line 55, in exec
    stderr=subprocess.PIPE,
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'node'
```

So I checked other related issues, but those solution doesn't seem to work for me.
Meanwhile, I also did some research, here is what I added for debugging purposes:

- Since `exec_command.py` is where the error is throwing, I added this:
![image](https://user-images.githubusercontent.com/13592559/150892736-1bec532d-93bb-477c-9596-7a0d2bcf8348.png)
- And since `NODE_BIN` originally comes from `import_helper.py`, I added these:
![image](https://user-images.githubusercontent.com/13592559/150892793-70c8cf55-bc22-4d10-a588-db4f11e3eada.png)

And here is the result (Note that none of the `if` block came into play):
![image](https://user-images.githubusercontent.com/13592559/150892857-21f4f585-2bf5-4551-830d-622480ddd8b1.png)

BTW I do have `node_bin` set up in config file:
![image](https://user-images.githubusercontent.com/13592559/150892912-3496fb18-1894-4b0d-b454-11be872709de.png)

It seems to me that in `import_helper.py` it is able to pick up the configuration, while in `exec_command.py`, the `node_bin` was reverted to default.

Am I missing anything? Or lemme know if you need other info from my side.

Thanks

**Comment by unlight** [comment]
Sorry, I don't know how to help. `node_bin` option should work. Try to open project and restart sublime.

**Comment by mhaecal** [comment]
the last option is change `NODE_BIN` value manually in `/home/USER/.config/sublime-text-3/Packages/ImportHelper/import_helper.py` to node executable

**Comment by puittenbroek** [comment]
You shouldn't rely on a global `NODE_BIN`. Simply have a helper that does what your `initialize` does.
So something like this:
```python


def get_node_executable():
    node_executable =  get_setting("node_bin", "")
    if not bool(node_executable):
        node_executable = find_executable("node")
    if not bool(node_executable):
        node_executable = NODE_BIN
    (err, out) = exec([node_executable, "--version"], None)
    version = float(".".join(out[1:].split(".")[0:2]))
    if version < 10:
        status_message("Node.js version is {0}, but 12+ is required".format(version))

    return node_executable
```

And then in exec_command:
```python

def run_command(command, data=None, callback=None):
    from ..import_helper import get_node_executable # prevent circular imports
    node_executable = get_node_executable()
    debug("run_command", [node_executable, command, data])
    json = sublime.encode_value({"command": command, "args": data})
    err = None
    out = None
    try:
        (err, out) = exec([node_executable, "--no-warnings", RUN_PATH], json)
    except Exception as e:
        err = traceback.format_exc()
    if bool(err):
        if callback is not None:
            return callback(err, None)
        raise Exception(err)
    # debug('run_command: trying to decode', out)
    result = sublime.decode_value(out)
    if callback is not None:
        return callback(None, result)
    return result
```
