### ISSUE TITLE
No imports found

### ISSUE THREAD

**Issue by cappncode** [unlight/sublime-import-helper#32]
I keep getting (eg) No imports found for 'Router'.
This might not be the place to ask for support....but what am I doing wrong ?
The plugin looks really great but I seem to have problems understanding how to configure it for proper-use.
Where and how to configure import_root and folders[i].path_source is a mystery to me right now.
Sorry if this is not the place to ask for support. But I couldn't find a better place!

Thnx in advance.
Jesper

**Comment by unlight** [comment]
Hard to say what is going wrong.

Possible wrong actions:
1. `Router` is not es2015/typescript file
2. No sublime-project

I may suggest enable debug mode:
1. Goto `Sublime-Text-3\Data\Packages\ImportHelper`
2. Open `utils.py` and comment `DEBUG = False` `# is comment for line in python`
3. Do `npm install` (inside Sublime-Text-3\Data\Packages\ImportHelper)
4. Restart sublime
5. Open sublime console (ctrl + `),  press ctrl + shift + p => `Update imports`

**Comment by cappncode** [comment]
Thnx for your reply….

I followed your instructions and after the restart and the “Update Imports”  I get the following error:

Import Helper
Traceback (most recent call last):
  File "/Users/jesperkoot/Library/Application Support/Sublime Text 3/Packages/ImportHelper/utils.py", line 30, in run_command
    (err, out) = exec(['node', RUN_PATH, command, json])
  File "/Users/jesperkoot/Library/Application Support/Sublime Text 3/Packages/ImportHelper/utils.py", line 53, in exec
    proc = subprocess.Popen(cmd, cwd=PACKAGE_PATH, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'node'


Is that any helpful for you ?!

Thnx again for you quick response !!

Grtz,

Jesper

**Comment by unlight** [comment]
Hm, do you have installed [node](https://nodejs.org/)?

**Comment by cappncode** [comment]
Yupz...
➜  ~ which node
/usr/local/bin/node
➜  ~ node -v
v7.9.0

**Comment by unlight** [comment]
So, the error is pretty clear
FileNotFoundError: [Errno 2] No such file or directory: 'node'
But the reason does not.

I've checked closed issues, no one encountered with this error.

**Comment by cappncode** [comment]
Do I have to change any settings in sublime itself...or do you have an example of config files or project files? Maybe that helps !?

**Comment by unlight** [comment]
You can try empty project (without any files and folders)
Than try to add one example ts file,
Do Update imports
You should see in console: N source modules found

I'll check people's similar issues:
https://github.com/73rhodes/Sublime-JSLint/issues/35
https://stackoverflow.com/questions/18014360/sublime-errno-2-no-such-file-or-directory-node

**Comment by cappncode** [comment]
Good News !!! I have it working....

It seems there was something wrong with the project file itself. It now works on new and existing projects.  Thnx for all the effort !!! And keep up the good stuff !

**Comment by salihaker** [comment]
Go to Settings > Predictions > Package Settings > Import Helper and on line 20 we find "node_bin": "",
And we do this "node_bin": "/path /for /you /node",
"node_bin": "/usr/local/bin/node", in my case
