### ISSUE TITLE
Handle export default

### ISSUE THREAD

**Issue by Herteby** [unlight/sublime-import-helper#34]
I think it should search for files with filenames that match the variable and have an `export default `statement. Maybe also search with camelCase converted to kebab-case.

**Comment by unlight** [comment]
`export default` [is supported](https://github.com/unlight/esm-exports/blob/8838747b9e608352ce3b4e6df99c654400a560d4/src/parse.spec.ts#L74-L79)
Please, provide your export default expression which does not work for you.

**Comment by Herteby** [comment]
Aah, sorry, the reason was that I had node 4 installed because I was working on a project that required it :smile:
