### ISSUE TITLE
[Feature] click filepath in import statement to go to it

### ISSUE THREAD

**Issue by Herteby** [unlight/sublime-import-helper#35]
Title says it all :smile:

**Comment by unlight** [comment]
I believe that ST3 has built in support.

**Comment by Herteby** [comment]
Hmm, I have ST3 and I don't see anything in the context menu when i right-click the path :thinking:

**Comment by unlight** [comment]
It is F12 goto definition command.
But anyway it is the job for another plugin, maybe such plugin already exists, try to find it here: https://packagecontrol.io/search/goto

Closing.
