### ISSUE TITLE
Will this remove unused imports?

### ISSUE THREAD

**Issue by wootwoot1234** [unlight/sublime-import-helper#36]
Will this remove unused imports?

**Comment by unlight** [comment]
No.

**Comment by unlight** [comment]
No.
Maybe possible in next major versions.

**Comment by unlight** [comment]
I changed my mind.
This feature will be in next minor release, because it requires in my current work.
But it will work through `tsc --noUnusedLocals` and only for typescript.
Javascript files not yet supported
https://github.com/Microsoft/TypeScript/issues/6802

**Comment by unlight** [comment]
Implemented in 1.6+
