### ISSUE TITLE
"There is no project file, Import Helper will not work without project"

### ISSUE THREAD

**Issue by wolfgangbecker** [unlight/sublime-import-helper#37]
Hi, I can't make the plugin work with Sublime Text Build 3143.
Right after installing and also after restarting Sublime, I get the message "There is no project file, Import Helper will not work without project".
Where does the project file need to be located, what name should it have and what goes into it?

Thanks in advance!

**Comment by unlight** [comment]
That's true, project file is required.
You must create project from your working files and folders, you can do it in top menu:
`Project -> Save project as...`
Save project file in any place you want.
Then restart Sublime.

**Comment by wolfgangbecker** [comment]
Awesome, it's working now. Thank you!
