### ISSUE TITLE
Can't complete suggestions with enter, can't ctrl+backspace

### ISSUE THREAD

**Issue by predragnikolic** [unlight/sublime-import-helper#38]
Before I begin, just to say I am glad you made this package. It is great :)

But there is a tiny problem or problems.
When I close a project, and open a random file, example `index.js` when I get completions, I can't complete them with enter.
Another problem I run into is that I can't ctrl+blackspace. 

All this works when I open a sublime project and then open `index.js`.

**Comment by unlight** [comment]
Hi.
This plugin cannot work without project.
And I did not get the point how plugin affect completions, it should not affect autocompletion feature.

**Comment by predragnikolic** [comment]
Steps to reproduce the problem. This will be interesting.
Open a new window in sublime `SHIFT+CTRL+N`.
Create a new file `index.html`.
Start typing `<htm` , i am getting a suggestion
![image](https://user-images.githubusercontent.com/22029477/31356339-fdc61156-ad3d-11e7-8ec5-f81f042c438e.png)
Pressing enter to complete the suggestion. Expecting to complete the suggestion but I isn't, need to press tab to complete the it. 
Want to press `CTRL+BACKSPACE` to delete a word. Expected behavior delete a word. Actual behavior the cursor is where he was and the word is not deleted.

Why I am reporting this to you. Well, I haven't had these, lets call them features, not problems :D
When I disable your plugin everything works as expected. Or when I have a project open, and your plugin is enabled everything works.

**Comment by unlight** [comment]
I still don't understand the issue.
`SHIFT+CTRL+N` opens new sublime text instance **without project file**.
As I sad earlier, ImportHelper doesn't work without project.
You should see message in status bar or in console `ctrl + ~`

**Comment by predragnikolic** [comment]
I understand that ImportHelper doesn't work without a project file, but if ImportHelper doesn't work, does it mean that when I open a `.css` file and get completion I can't complete them with the `Enter` key, as I could when your package is not enabled?
