### ISSUE TITLE
No imports found for 'Routes'

### ISSUE THREAD

**Issue by JoshuaKin** [unlight/sublime-import-helper#44]
when writing angular

**Comment by unlight** [comment]
1. Is the behavior same after Update modules command?
2. Are you using project file?

**Comment by JoshuaKin** [comment]
I built the project by terminal ,
And the plug-in cant used everywhere ，all show me ‘No imports found for... ’ 
nodejs installed.
On 10/29/2017 02:17, Roman Vasilev wrote:
Is the behavior same after Update modules command?
Are you using project file?

**Comment by unlight** [comment]
By asking `Are you using project file?` I mean that plugin need to know root path where start to search module.
Try to restart ST3 and if you see message in console and in status bar:
```
There is no project file, ... will not work without project.
```
That means what it means, you need save you work files to project.
See #37

```
You must create project from your working files and folders, you can do it in top menu:
`Project -> Save project as...`
Save project file in any place you want.
Then restart Sublime.
```

**Comment by JoshuaKin** [comment]
yeah~I’ve got it!
THX for a lot for your help.

By the way, could u recommend some plugins about typescript competition or snippets ,or angular snippets .Thanks!!:)





发自网易邮箱大师
On 10/29/2017 02:49, Roman Vasilev wrote:

By asking Are you using project file? I mean that plugin need to know root path where start to search module.
Try to restart ST3 and if you see message in console and in status bar:

There is no project file, ... will not work without project.


That means what it means, you need save you work files to project.
See #37

You must create project from your working files and folders, you can do it in top menu:
`Project -> Save project as...`
Save project file in any place you want.
Then restart Sublime.
