### ISSUE TITLE
Add setting for semicolon usage

### ISSUE THREAD

**Issue by katanacrimson** [unlight/sublime-import-helper#46]
As semicolons (in some style guides) are not even optional, but are required to be omitted (see StandardJS), semicolon usage ought to be something configurable in this plugin.

(Aside: nicely done, seems to work well. Thanks for your creation!)

**Comment by unlight** [comment]
Just implemented in v1.7.5, wait a few hours until package will be updated by packagecontrol.io

**Comment by unlight** [comment]
[Just implemented in v1.7.5](https://github.com/unlight/sublime-import-helper#from_semicolon), wait a few hours until package will be updated by packagecontrol.io
