### ISSUE TITLE
Cannot import from node_module

### ISSUE THREAD

**Issue by xihaoxiaohao** [unlight/sublime-import-helper#49]
I saved as project of my angular app, and it can auto import my files inside the src folder, but not outside like node_module. How can I setup like the demo gif's setting that it can auto import angular modules?

<img width="334" alt="a" src="https://user-images.githubusercontent.com/9826637/35375942-be5173de-015d-11e8-926f-b1e97c22b696.png">

**Comment by unlight** [comment]
It is probably bug, but most likely you are not using project file, please check FAQ section
https://github.com/unlight/sublime-import-helper#faq

**Comment by xihaoxiaohao** [comment]
I did create a project file, do you mind share your project file settings? thanks.

**Comment by unlight** [comment]
I do not have any specific settings for plugin. Just defaults.
Can you provide your package.json?

Also to figure out the problem, I can advice you enable debug mode:
https://github.com/unlight/sublime-import-helper/issues/32#issuecomment-303237359
```
1. Goto `Sublime-Text-3\Data\Packages\ImportHelper`
2. Open `utils.py` and comment `DEBUG = False` `# is comment for line in python`
3. Do `npm install` (inside Sublime-Text-3\Data\Packages\ImportHelper)
4. Restart sublime
5. Open sublime console (ctrl + `),  press ctrl + shift + p => `Update imports`
```

**Comment by xihaoxiaohao** [comment]
Here is what I did, I also update the import, but still don't see the Component module from the selection, I can only see the module from the src folder.
![a](https://user-images.githubusercontent.com/9826637/35719211-296e359a-079d-11e8-970a-0fd0b5b6d4cd.gif)


Here is my package.json:

```
{
  "name": "webcomics",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.1.0",
    "@angular/common": "^5.1.0",
    "@angular/compiler": "^5.1.0",
    "@angular/core": "^5.1.0",
    "@angular/forms": "^5.1.0",
    "@angular/http": "^5.1.0",
    "@angular/platform-browser": "^5.1.0",
    "@angular/platform-browser-dynamic": "^5.1.0",
    "@angular/router": "^5.1.0",
    "@angular/service-worker": "^5.1.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.9",
    "bootstrap": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "1.6.5",
    "@angular/compiler-cli": "^5.1.0",
    "@angular/language-service": "^5.1.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
```

and after enable debug, here is the log:
```
source_folders: ['/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend']
import_root: /Users/xihao/sublimeProjects
Run command: ['/usr/local/bin/node', 'get_folders', {'folders': ['/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend']}]
Run command: ['/usr/local/bin/node', 'get_modules', {'packageKeys': ['devDependencies'], 'importRoot': '/Users/xihao/sublimeProjects'}]
Run command: ['/usr/local/bin/node', 'get_modules', {'packageKeys': ['dependencies'], 'importRoot': '/Users/xihao/sublimeProjects'}]
Trying to decode: []Trying to decode: []

Get packages result: 0
Get packages result: 0
Trying to decode: [{"name":"AppPage","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/e2e/app.po.ts"},{"name":"environment","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/environments/environment.prod.ts"},{"name":"environment","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/environments/environment.ts"},{"name":"AppRoutingModule","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/app-routing.module.ts"},{"name":"AppComponent","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/app.component.ts"},{"name":"AppModule","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/app.module.ts"},{"name":"BsNavbarComponent","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/bs-navbar/bs-navbar.component.ts"},{"name":"HomePageComponent","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/home-page/home-page.component.ts"},{"name":"SigninPageComponent","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/signin-page/signin-page.component.ts"},{"name":"SignupPageComponent","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/signup-page/signup-page.component.ts"},{"name":"ComicModule","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/comic/comic.module.ts"},{"name":"ComicService","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/comic/comic.service.ts"},{"name":"Volume","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/comic/comic.ts"},{"name":"Chapter","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/comic/comic.ts"},{"name":"Page","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/comic/comic.ts"},{"name":"Comic","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/comic/comic.ts"},{"name":"ComicReaderComponent","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/comic/comic-reader/comic-reader.component.ts"},{"name":"ComicUploadComponent","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/comic/comic-upload/comic-upload.component.ts"},{"name":"ComicDetailComponent","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/comic/comic-detail/comic-detail.component.ts"},{"name":"ComicListComponent","isDefault":false,"filepath":"/Users/xihao/Desktop/github/CS115Team/Webcomics-Frontend/src/app/comic/comic-list/comic-list.component.ts"}]
Update source modules: 20
Selected word region: Component
```

**Comment by unlight** [comment]
It works for me. I'm able to see all angular/rx/other modules in the list.

Did you do `npm install`?
Does `node_modules` folder contains something?
Are you using non-standard package manager (pnpm, ied)?

**Comment by xihaoxiaohao** [comment]
I created a new angular project and it worked on the new project, maybe my old project have some weird settings...

**Comment by ohabash** [comment]
@xihaoxiaohao @unlight 
First: great plugin!

My problem is same. node_modules are not in the modules list. is there a way to force it? Could it have anything to do with node_modules being on many ignore lists

I also installed import helper after the project had already been created.

**Comment by unlight** [comment]
@ohabash 
Try [Update Imports](https://github.com/unlight/sublime-import-helper#update-imports) command (this force update list of node modules and source modules)

**Comment by ohabash** [comment]
@unlight I should have mentioned that i am doing that. No luck though. only source modules are added. but 0 node_modules

**Comment by unlight** [comment]
Hmm, maybe plugin cannot find modules (only typescript and es2015 are supported).
Can you provide contents of your `package.json`?

**Comment by ohabash** [comment]
so my project has a nodejs server and the angular app... At the root is my servers `package.json` (none of those are in the list either) it looks like

    {
      "name": "fornida-prototype",
      "version": "1.0.0",
      "description": "",
      "main": "server.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "start": "node server.js"
      },
      "author": "",
      "license": "ISC",
      "dependencies": {
        "body-parser": "^1.18.2",
        "cors": "^2.8.4",
        "express": "^4.16.3",
        "firebase-admin": "^5.11.0",
        "mongodb": "^3.0.4",
        "mongoose": "^5.0.11",
        "node-bigcommerce": "^3.0.0"
      }
    }


and in `(root)/client` is my angular app. It has a `package.json` looks like this 

        {
          "name": "cloudnav",
          "version": "0.0.0",
          "license": "MIT",
          "scripts": {
            "ng": "ng",
            "start": "ng serve",
            "build": "ng build --prod",
            "test": "ng test",
            "lint": "ng lint",
            "e2e": "ng e2e"
          },
          "private": true,
          "dependencies": {
            "@angular/animations": "^5.2.0",
            "@angular/common": "^5.2.0",
            "@angular/compiler": "^5.2.0",
            "@angular/core": "^5.2.0",
            "@angular/forms": "^5.2.0",
            "@angular/http": "^5.2.0",
            "@angular/platform-browser": "^5.2.0",
            "@angular/platform-browser-dynamic": "^5.2.0",
            "@angular/router": "^5.2.0",
            "@spacebar/ngx-datatables": "^0.2.1",
            "@types/vanilla-modal": "^1.6.1",
            "angular-particle": "^1.0.4",
            "angular2-fontawesome": "^5.2.1",
            "angularfire2": "^5.0.0-rc.6",
            "core-js": "^2.4.1",
            "datatables.net": "^1.10.16",
            "datatables.net-dt": "^1.10.16",
            "datatables.net-select": "^1.2.5",
            "firebase": "^4.11.0",
            "font-awesome": "^4.7.0",
            "jquery": "^3.3.1",
            "jquery-parallax.js": "^1.5.0",
            "ngx-slick": "^0.1.3",
            "particler": "^0.1.2",
            "particles.js": "^2.0.0",
            "rellax": "^1.6.0",
            "rxjs": "^5.5.6",
            "sticky-js": "^1.2.0",
            "tilt.js": "^1.2.1",
            "vanilla-tilt": "^1.4.1",
            "zone.js": "^0.8.19"
          },
          "devDependencies": {
            "@angular/cli": "^1.7.3",
            "@angular/compiler-cli": "^5.2.0",
            "@angular/language-service": "^5.2.0",
            "@types/datatables.net": "^1.10.8",
            "@types/jasmine": "~2.8.3",
            "@types/jasminewd2": "~2.0.2",
            "@types/jquery": "^3.3.1",
            "@types/node": "~6.0.60",
            "@types/vanilla-tilt": "^1.4.0",
            "codelyzer": "^4.0.1",
            "jasmine-core": "~2.8.0",
            "jasmine-spec-reporter": "~4.2.1",
            "karma": "~2.0.0",
            "karma-chrome-launcher": "~2.2.0",
            "karma-coverage-istanbul-reporter": "^1.2.1",
            "karma-jasmine": "~1.1.0",
            "karma-jasmine-html-reporter": "^0.2.2",
            "protractor": "~5.1.2",
            "ts-node": "~4.1.0",
            "tslint": "~5.9.1",
            "typescript": "~2.5.3"
          }
        }

**Comment by unlight** [comment]
Also please contents of the your `.sublime-project` file.

**Comment by unlight** [comment]
@ohabash 
Probably your `package.json` in subfolder (client). This folder is supposed to be root.
So your sublime project file should looks like:
```
{
  "folders": [
    {
      "path": "./client"
    },
  ]
}
```
But if you have multiple folders in your project (e.g. `server` and `client`) than you can import from node_modules only from 1 sub-folder - you must explicitly set `import_root`:
https://github.com/unlight/sublime-import-helper#import_root-project-file-only, for example:
```
{
  "folders": [
    {
      "path": "."
    },
  ],
  "import_root": "./client",
}
```

**Comment by ohabash** [comment]
Nice that works. Will never write an import statement again! (used the 2nd option)

**Comment by PCatinean** [comment]
Hi and thank you for this really nice plugin (stopped me from changing editors).

I have the same issue as the guys above, tried it all, even the latest solution "import_root" and it seems to have no effect after I update modules. 

The debug mode shows how it traverses all directories from my root including my personal modules but not the standard ones from angular. Not sure how to proceed
