### ISSUE TITLE
export default doesn't work

### ISSUE THREAD

**Issue by ghost** [unlight/sublime-import-helper#51]
Here is my working import
`import SettingsContainer from '../../containers/Dashboard/SettingsContainer`
Here is export default:
```
class SettingsContainer extends React.Component {
	render() {
		return <SettingsContent />
	}
}

export default SettingsContainer 
```
[And i got this](https://imgur.com/a/kyKQQ)
And this is not only one issue. Sometimes after restarting sublime I need to recreate project file to make it work.
Here is my config: 
```
{
	"insert_position": "end",
	"from_quote": "'",
	"space_around_braces": true,
	"node_bin": "/usr/local/bin/node",
	"from_semicolon": true
}

```
I hope you will help. 
P.S: Sorry for my bad english.

**Comment by unlight** [comment]
Fix will be shipped with v1.8.1
