### ISSUE TITLE
Support of auto_complete

### ISSUE THREAD

**Issue by Appius** [unlight/sublime-import-helper#57]
Hello,

It would be really good to see support of auto_complete functionality.
When you try to type something, sublime suggests a list of auto_completes, it should contain list of possible auto imports (from your "List imports") and when you choose something, it should be automatically auto-imported.

I can try to implement it by myself and create a pull request.

Thanks.

**Comment by unlight** [comment]
Unfortunately, there is no API to detect what was selected from autocomplete list.
So technically `auto-import` is possible but it will take more effort.

**Comment by Appius** [comment]
The first attempt was made this weekend and I was able to add auto-suggestions to the list (see this [commit](https://github.com/Appius/sublime-import-helper/commit/37f4471e3b35b54fc8ad451c254df289c7b4332a)).

What I have not figured out yet, is how to filter auto-completion - _when_ do you need to add possible variants?
Right now when you try to type anything on the new line, it suggests possible variants perfectly fine (with a couple of duplicates, but it could be overcomed). But it also adds a list when you try to access an object's properties (e.g. via `.`). Will try to figure it out in the next couple days.

If you have any ideas or comments, will be glad to hear.

**Comment by unlight** [comment]
Thanks for example.
I've started implementation.
There is another feature in development #54, I will release both with next release.

**Comment by unlight** [comment]
Autocomplete feature is implemented in v2.0.0+, but auto import is not enabled by default.
https://github.com/unlight/sublime-import-helper#autocomplete_auto_import
