### ISSUE TITLE
Update source modules add keymap

### ISSUE THREAD

**Issue by Nemesis19** [unlight/sublime-import-helper#58]
Dear developer,

could you add a keypam to the command "Update source modules"? it can be very helpful to quickly update the sources and import correctly new models/components etc...

thanks

**Comment by unlight** [comment]
@Nemesis19 
You can bind by editing `Data\Packages\User\Default (Windows).sublime-keymap` file
Top Menu -> Preferences -> Key binding:
Add to the end:
```
    {
        "keys": ["alt+i", "alt+s"],
        "command": "update_source_modules",
        "context": [
            { "key": "selector", "operator": "equal", "operand": "source.ts, source.tsx, source.js, source.jsx" }
        ]
    }
```

**Comment by Nemesis19** [comment]
Simply awesome

**Comment by unlight** [comment]
Added in 2.0.1
