### ISSUE TITLE
Option to remove 'index' from the import path.

### ISSUE THREAD

**Issue by bobpearson** [unlight/sublime-import-helper#59]
It is common to place an index.js file in a module directory to be a single point of contact for exports from the module.   If the path to the index is:

```
/a/b/c/index.js
```
then
```
import { something } from "/a/b/c";
```
is sufficient.   An option to trim a final '/index' from a path would be a nice feature.

Can this be done with path mapping?   If so, I did not find it.

**Comment by unlight** [comment]
Feature will be shipped in next version, with enabled by default state.
I need some time to test it.

**Comment by unlight** [comment]
Released in v2.0.2
