### ISSUE TITLE
Error in importing modules in Angular6 app

### ISSUE THREAD

**Issue by Afzal7** [unlight/sublime-import-helper#60]
Hi guys, good job on the plugin really helps a lot. I just get this issue everytime i do a fresh install. So i have created a sublime project file and restarted sublime. After that, this was the error in the sublime terminal:

> Traceback (most recent call last):
  File "/home/afzal/.config/sublime-text-3/Packages/ImportHelper/import_helper.py", line 30, in setup
    update_typescript_paths()
  File "/home/afzal/.config/sublime-text-3/Packages/ImportHelper/import_helper.py", line 77, in update_typescript_paths
    for path_to, pathValues in paths.items():
AttributeError: 'NoneType' object has no attribute 'items'

I have fixed this with a simple if condition as follow:

> paths = compilerOptions.get('paths')
        if paths:
            for path_to, pathValues in paths.items():
                for path_value in pathValues:
                    typescript_paths.append({'base_dir': base_dir, 'path_value': path_value, 'path_to': path_to})

Everything is working fine now.

Please advice.

Using Ubuntu 18.04 btw.

Thanks.

**Comment by unlight** [comment]
Hi.
Thanks for bug report, I'll fix that.
As a workaround you can add  `"paths": {}` to your `tsconfig.json -> compilerOptions`
