### ISSUE TITLE
Is it possible to make it work without project?

### ISSUE THREAD

**Issue by kud** [unlight/sublime-import-helper#69]

**Comment by unlight** [comment]
Without effort - no.
There are many open questions if open file outside from the project:
- Scan files to descendant files/folder only
- Scan parent folders? How to detect root, when to stop (tsconfig.json, jsconfig.json)
- What files/folder should be ignored

**Comment by kud** [comment]
Interesting, thank you for the answer.

I'll go deeper into projects, I don't use 'em all but it could help me at the end.

**Comment by unlight** [comment]
@kud 
Please check version `3.0.0`

**Comment by kud** [comment]
eesh :D I switched to VS Code since. 😬

I'll try again.
