### ISSUE TITLE
React-native tag imports don't work

### ISSUE THREAD

**Issue by rafaumeu** [unlight/sublime-import-helper#72]
![Captura de tela_2019-10-30_23-52-07](https://user-images.githubusercontent.com/30784471/67915491-ef872b00-fb71-11e9-8eba-e4080b201e5a.png)
Even using package shortcuts, tags are not recognized and do not import, only manually. Error: import not found for.

**Comment by unlight** [comment]
react-native is referencing to `node_modules/react-native/Libraries/react-native/react-native-implementation.js` which is not es2015 or typescript file.

Try to install `@types/react-native`

**Comment by rafaumeu** [comment]
It worked

**Comment by rafaumeu** [comment]
any suggestions for working with react?

**Comment by unlight** [comment]
Same. Install `@types/react`
