### ISSUE TITLE
Typescript compiler error when removing unused imports

### ISSUE THREAD

**Issue by thepigeonoftime** [unlight/sublime-import-helper#78]
Hi,
when trying to remove unused imports I'm getting 

`    Import Helper    
    Error while running typescript compiler:    
    Error: spawn node_modules/.bin/tsc ENOENT    
        at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)    
        at onErrorNT (internal/child_process.js:467:16)    
        at processTicksAndRejections (internal/process/task_queues.js:84:21) {    
      errno: -2,    
      code: 'ENOENT',    
      syscall: 'spawn node_modules/.bin/tsc',    
      path: 'node_modules/.bin/tsc',    
      spawnargs: [    
        '/Users/example/src/Example.tsx',    
        '--noEmit',    
        '--pretty',    
        'false',    
        '--noUnusedLocals',    
        '--allowJs'    
      ]    
    }    `

Any idea what causes this?

**Comment by unlight** [comment]
code `ENOENT` means no such file, looks like you do not have `node_modules/.bin/tsc` file in your project, `tsc` comes from `typescript`.

Do you have `package.json`? Did you do `npm install`?

Btw, `Remove unused import` command was removed since version 3.0.0

**Comment by unlight** [comment]
Or use 'organize imports' command from typescript plugin
