### ISSUE TITLE
released 3.0.0 has broken all functionality for me

### ISSUE THREAD

**Issue by mattbourke** [unlight/sublime-import-helper#80]
Hi, 
Normally a great package, thanks for this. 

Today my sublime upgraded this package to 3.0.0
Now when I run things like "list imports" and "update source modules" (my regular commands) 
I get errors like the below.  - I'm on a Mac, running node 10.21.0 via nvm. Sublimetext version Build 3211
```
error: Import Helper
(node:32007) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
--- Exec error ---
(node:32011) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time

error: Import Helper
(node:32011) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
--- Exec error ---
(node:32012) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time```

**Comment by unlight** [comment]
Hi, version 3.0.0 fequires modern version of nodejs 10+

**Comment by mattbourke** [comment]
I'm running  10.21.0 which is lts/dubnium so latest version of 10, or do you mean 11+?

**Comment by unlight** [comment]
12+ is better -) Sorry, experimental flag for Readable[Symbol.asyncIterator] was removed in 11.4+ https://github.com/nodejs/node/pull/26989/files

In `3.0.1` I added `--no-warnings` to node args, should work in node `10.0.0` without errors

**Comment by mattbourke** [comment]
Thanks a lot, I'll be sure to grab it :D

**Comment by mattbourke** [comment]
I'm not sure what is involved with publishing sublimetext packages, how long should I expect until it's available on package control?

**Comment by unlight** [comment]
Approximately ~ 1 hour, but sometimes it can take up to 3 hours.

**Comment by mattbourke** [comment]
Thanks, I'll let you know tomorrow how it goes. 
спокойной ночи

**Comment by mattbourke** [comment]
Awesome work!, that fixed it for me, once again thanks for the great package. 
On another note: I have found in the past it can get bogged down by date-fns when updating source modules, if I see it again I'll raise a ticket.
