### ISSUE TITLE
Error: Unknown command exportsFromFolder

### ISSUE THREAD

**Issue by gergof** [unlight/sublime-import-helper#81]
Since the latest update I have the following error when running the _Update Source Modules_ command:
![image](https://user-images.githubusercontent.com/10323997/84662916-1ccbf200-af25-11ea-997e-1cf7f65bbdd8.png)

**Comment by unlight** [comment]
Looks like something went wrong while updating process.

Try to reinstall package.

If problem stays, try to download release from github https://github.com/unlight/sublime-import-helper/releases and update files manually

**Comment by gergof** [comment]
Removing and reinstalling didn't work, but installing it manually did the trick. Thank you for the help!
