### ISSUE TITLE
Cannot find module for ...

### ISSUE THREAD

**Issue by ConnorVO** [unlight/sublime-import-helper#82]
My folder setup is:

```
<project>
--frontend
----<project>
------node_modules
--backend

```
If I set my <project>.sublime-settings as below, it will import things from node_modules but will not import any of my own models.
`
"folders":
	[
		{
			"path": "./frontend/django-angular-heroku-discord"
		}
	],
`

However, If I set my .sublime-settings with a path of '.' and try to use import_root with the above filepath, it doesn't work at all.

Also, if I just set the path to '.' and do nothing else, it also doesn't work. It appears that the sublime-settings needs to be at the same level as the node_modules, but it still won't import any of my own exports created in the app

**Comment by unlight** [comment]
I'm not sure that I fully understand context, but I will try clarify for my self by asking you several questions.

- You have 1 folder in your project file with 2 folders, correct?
- Do you have `folder_exclude_patterns` or `file_exclude_patterns` settings for folders in project file?
- Is `django-angular-heroku-discord` javascript or typescript project?
- Does this project `django-angular-heroku-discord` have tsconfig.json or jsconfig.json?
- After changing `folders[i].path` to frontend/django-angular-heroku-discord, do you re-initialize plugin (`Import Helper: Initialize / Setup / Update modules` from command palette)?

And here is the description how module detection works:
source folder will be scanned for all js/ts files, unless it have tsconfig.json or jsconfig.json, in this case files will be addding according to tsconfig rules
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
(files, include, exclude, etc.)

**Comment by ConnorVO** [comment]
I have the below folder structure.
```
<root_folder>
--<project_name>.sublime-project
--backend
--frontend
----<angular_app_name>
------node_modules
------e2e
------src
```

My .sublime-project file is below:
```
{
    "build_systems":
        [
	    {
	        "file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
		"name": "Anaconda Python Builder",
		"selector": "source.python",
		"shell_cmd": "\"python\" -u \"$file\""
	    }
	],
	"folders":
	[
	    {
		"path": "."
	    }
	]
}
```


It does not work at all with the above settings. However, if I change the path to the same directory as node_modules, it works for importing items from the node_modules folder but still doesn't work for any of my custom components, models, etc.
```
"folders":
    [
        {
	    "path": "./frontend/<angular_app_name>"
        }
    ]
```

I do have a tsconfig in my angular app, but I do not have any includes or excludes.

Yes, I run `Import Helper: Initialize / Setup / Update modules` everytime I make a change to the sublime-settings folder

**Comment by unlight** [comment]
Sorry, but I couldn't reproduce this behavior.
