### ISSUE TITLE
Unknown command exportsFromFolders

### ISSUE THREAD

**Issue by mattbourke** [unlight/sublime-import-helper#83]
When I run the command `Import Helper: Update source modules` I get the following error

Import Helper
Error: Unknown command exportsFromFolders
    at ./node_modules/import-adjutor/cli.js (/Users/mymachine/Library/Application Support/Sublime Text 3/Packages/ImportHelper/backend_run.js:11989:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Using node lts/erbium (providing my sublime text settings are working correctly). 
macos
sublime text 3 latest stable release.

**Comment by mattbourke** [comment]
seems to now be fixed on my machine, but not sure because I went around installing version 1.2.0 of this globally or not...
be interesting to see if others get it. https://github.com/unlight/import-adjutor/blob/eafc833967fb6dc53c43fdfb89643aaa8183fc83/CHANGELOG.md 
I also installed the latest version too. so not sure if my error was a one off or not... 
I noticed your package.json has import-adjutor in it, then went to the changelog above and seen the exportsFromFolders has been deprecated in 2.0.0

Perhaps this doesn't need to be 2.0.0? https://github.com/unlight/sublime-import-helper/commit/bbbd4c429294ec8d5b515d294e6fbec19d182161#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R16

**Comment by unlight** [comment]
`exportsFromFolders` was removed from ImportHelper in 3.0.2
https://raw.githubusercontent.com/unlight/sublime-import-helper/v3.0.2/backend_run.js (no exportsFromFolders there)

I did not get you about install version globally (of what?) You do not need install additional modules, everything is bundled.

**Comment by mattbourke** [comment]
ok no worries, I think it must have fixed its self.
