### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by bartoszkrawczyk2** [unlight/sublime-import-helper#89]
Hi, I'm getting this error:
<img width="532" alt="Zrzut ekranu 2020-10-1 o 17 38 04" src="https://user-images.githubusercontent.com/7081383/94831525-1ba7cd80-040d-11eb-9775-5d0c41579bef.png">

ImportHelper version: 3.1.0
Sublime Text version: 3.2.2

Any idea how to solve it?

**Comment by unlight** [comment]
What version of node.js are you using?
Node.js 10+ is required

**Comment by bartoszkrawczyk2** [comment]
10.15.1

**Comment by unlight** [comment]
I tested with 10.0.0 and it worked for me.
I'll retest it. Right now, I can suggest to update to latest version - 14.

**Comment by unlight** [comment]
#84 Similar issue
