### ISSUE TITLE
node_bin setting ignored

### ISSUE THREAD

**Issue by mjasnikovs** [unlight/sublime-import-helper#91]
![image](https://user-images.githubusercontent.com/12757881/96223347-6f322380-0f96-11eb-9298-10d6cd509f7b.png)

```sh
edgars@lvdobdskd2zd8x2:/home$ which node
/home/edgars/.nvm/versions/node/v10.22.1/bin/node
```

node_bin setting ignored ¯\_(ツ)_/¯

And when I manually fixed this bug...

![image](https://user-images.githubusercontent.com/12757881/96225172-5f680e80-0f99-11eb-94e7-09c8045ca2dd.png)

**Comment by unlight** [comment]
Is `/home/emja/hub` folder exists?
Probably node.js do not have permissions to view it.

**Comment by unlight** [comment]
I cannot reproduce it.
Setting `node_bin` in `Data\Packages\User\import_helper.sublime-settings` is reflected correctly and plugin uses it.
Try to restart sublime_text after changing.

Btw, `which node` in sublime console does not make sense.

**Comment by mjasnikovs** [comment]
Closed, i found a working alternative.
