### ISSUE TITLE
File not found Exception

### ISSUE THREAD

**Issue by passelord** [unlight/sublime-import-helper#93]
Hello,

I thank you for your plugin. I have an error when I start SublimeText or when I try to use some functionality of Import Helper (initialize / setup / update modules and update source modules).
There is a screenshot.
The sentence "Le fichier spécifié est introuvable" means "The specified file is not found".

Thank you for your help.

![image](https://user-images.githubusercontent.com/50640833/100326093-ce3d7c00-2fc9-11eb-949b-1ee0134dd300.png)

**Comment by passelord** [comment]
P.S. : I am coding in Java. If you have any question, tell me.

**Comment by unlight** [comment]
Hello.
1. Do you have node.js installed on you system? If yes, probably [configuring node_bin](https://github.com/unlight/sublime-import-helper#node_bin) may help.
2. If you language is Java, plugin will not work. 
  https://github.com/unlight/sublime-import-helper#supported-languages
  Supported languages:
    - TypeScript
    - JavaScript (ES2015)

**Comment by passelord** [comment]
Ho! Sorry I believed that Java was supported... Sorry for the disturbing.
